[versions]
vanillaGradle = "0.2.1-SNAPSHOT"
adventure = "4.24.0-SNAPSHOT"

[libraries]
adventureNbtSerializer = { module = "net.kyori:adventure-text-serializer-nbt", version.ref = "adventure" }

[plugins]
vanillaGradle = { id = "org.spongepowered.gradle.vanilla", version.ref = "vanillaGradle" }